WeatherStateMachine {
 States {
  SCR_WeatherState "{69300B207C7DEBBB}" {
   UiLocalizedName "CombatStorm"
   UiIcon "{FD76D25703F65EC8}UI/Textures/Editor/Attributes/Weather/Attribute_Weather_Stormy.edds"
   StateName "Combat Storm"
   WeatherVariant0 WeatherVariant "{69352C4CEFA69BFE}" {
    VariantName "Base"
    WindPattern WeatherWindPattern "{69352C4CEFC2F6D6}" {
     WindSpeedMax 0.1
    }
    RainPattern WeatherRainPattern "{69352C4CFDC1E4E7}" {
    }
    FogPattern WeatherFogPattern "{69352C4CC394508B}" {
     FogMinAmount 0.1
     FogMaxAmount 0.2
     FogMinHeight 0.1
     FogMaxHeight 0.2
    }
    LightningPattern WeatherLightningPattern "{69352C4CC9C4D817}" {
     LightningFrequencySeconds 60
     LightningPerturbationRangeSeconds 50
    }
    WeatherItems WeatherItems "{69352C4D2287FC5A}" {
     SunLightingParams {
      0
      0
      0
      -55.735
      1
      0
      1
      0
      -55.735
      0.936
      0
      2
      0
      -55.735
      0.689
      1
      0
      0
      -51.398
      11.86
      6
      0
      0
      4.988
      0.866
      2
      0
      0
      9.325
      0.86
      2
      1
      0
      9.325
      0.727
      2
      2
      0
      9.325
      0.727
      3
      0
      0
      -17.566
      0.846
      7
      0
      0
      -18.434
      4.419
      8
      0
      0
      -25.807
      4.826
      9
      0
      0
      -8.892
      0.953
      9
      1
      0
      -8.892
      0.953
      9
      2
      0
      -8.892
      0.953
      10
      0
      0
      -29.711
      0.983
      10
      1
      0
      -29.711
      0.983
      10
      2
      0
      -29.711
      0.983
      4
      0
      0
      -27.542
      0.983
      5
      0
      0
      -2.386
      0.448
      45
      0
      0
      7.59
      0.442
      77
      0
      0
      6.723
      0.741
     }
     MoonLightingParams {
      0
      0
      0
      -54
      0.826
      0
      1
      0
      -54
      0.933
      0
      2
      0
      -54
      0.968
      1
      0
      0
      -29.711
      8.372
     }
     SunCameraParams {
      11
      0
      0
      -18
      3.837
      16
      0
      0
      -37.084
      0.913
      12
      0
      0
      -25.373
      9.419
      13
      0
      0
      -43.59
      -8.488
     }
     SunAtmosphereParams {
      14
      0
      0
      -48.361
      20
     }
    }
   }
  }
 }
 StartState "Clear"
}