WeatherStateMachine {
 States {
  SCR_WeatherState "{69300B207C7DEBBB}" {
   UiLocalizedName "CombatStorm"
   UiIcon "{FD76D25703F65EC8}UI/Textures/Editor/Attributes/Weather/Attribute_Weather_Stormy.edds"
   StateName "Combat Storm"
  }
 }
 StartState "Clear"
}