SCR_MissionHeader {
 World "{1DE7F644047EF4D3}Worlds/GM_BFABelleauWood3.ent"
 m_sName "Battlefleet Armageddon Belleau Wood"
 m_sDescription "Edits to the Belleau Wood Map for Battlefleet Armageddon Operations"
 m_sIcon "{46E12D8F5F3B31E7}Assets/Props/Fabric/Flags/Data/BattlefleetArmageddon_Flag_01.edds"
 m_sLoadingScreen "{46E12D8F5F3B31E7}Assets/Props/Fabric/Flags/Data/BattlefleetArmageddon_Flag_01.edds"
 m_sPreviewImage "{46E12D8F5F3B31E7}Assets/Props/Fabric/Flags/Data/BattlefleetArmageddon_Flag_01.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_bRandomStartingDaytime 1
 m_bRandomWeatherChanges 1
 m_bMapMarkerEnableDeleteByAnyone 1
}