SCR_MissionHeader {
 World "{6AED9ECCF0DC1BA3}Worlds/GM_BFABelleauWood2.ent"
 m_sName "Battlefleet Armageddon Belleau Wood"
 m_sDescription "Edits to the Belleau Wood Map for Battlefleet Armageddon Operations"
 m_sIcon "{46E12D8F5F3B31E7}Assets/Props/Fabric/Flags/Data/BattlefleetArmageddon_Flag_01.edds"
 m_sLoadingScreen "{46E12D8F5F3B31E7}Assets/Props/Fabric/Flags/Data/BattlefleetArmageddon_Flag_01.edds"
 m_sPreviewImage "{46E12D8F5F3B31E7}Assets/Props/Fabric/Flags/Data/BattlefleetArmageddon_Flag_01.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_bRandomStartingDaytime 1
 m_bRandomWeatherChanges 1
 m_bMapMarkerEnableDeleteByAnyone 1
 m_ACE_Settings ACE_MissionHeaderSettings "{694F71E9E6679C92}" {
  m_ACE_Medical_Core ACE_Medical_Core_Settings "{694F71E9E45EC136}" {
  }
  m_ACE_Medical_Circulation ACE_Medical_Circulation_Settings "{694F71E9E1281608}" {
   m_CardiacArrestDamageEffect ACE_Medical_CardiacArrestDamageEffect "{694F71E9EC581B76}" {
   }
  }
  m_ACE_Medical_Medication ACE_Medical_Medication_Settings "{694F71E9EB0F144F}" {
  }
  m_ACE_Medical_Breathing ACE_Medical_Breathing_Settings "{694F71E9EA5E4BC0}" {
  }
  m_ACE_Medical_Hitzones ACE_Medical_Hitzones_Settings "{694F71E9E98C945F}" {
  }
 }
}