SCR_MissionHeader {
 World "{C7F6B7B7DC019C4D}Worlds/Gamemaster/Belleau_Wood_GM.ent"
 m_sName "Cadian 8th Belleau Wood"
 m_sDescription "Edits to the Belleau Wood Map for Cadian 8th Operations"
 m_sIcon "{315CAAAC34F2A0AB}Images/Cadian_8th_Flag.edds"
 m_sLoadingScreen "{F55E643C9E6B6B44}UI/Cadian_8th_Flag.edds"
 m_sPreviewImage "{315CAAAC34F2A0AB}Images/Cadian_8th_Flag.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_bRandomStartingDaytime 1
 m_bRandomWeatherChanges 1
 m_bMapMarkerEnableDeleteByAnyone 1
}